# mamba env create --force -f /Users/bobcolner/QuantClarity/sopadilo/dev_ops/conda_quant.yaml
# mamba env update -n quant -f dev_ops/conda_quant.yaml
name: quant
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.9
  - blas = *=mkl
  - psutil
  - mamba
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - bokeh
  - pyarrow
  - cytoolz
  - pandas
  - pandas-profiling
  - ipython
  - ipdb
  - jupyterlab
  - nodejs
  - jupyterlab-git
  - nbdime
  - mamba_gator
  - jupyterlab_execute_time
  - dask
  - tqdm
  - requests
  - fsspec
  - s3fs
  - boto3
  - pip
  - pip:
    - pandas-bokeh
    - graphviz
    - finplot
    - 'ray[default]'
    - 'prefect[viz]'
    - pandas_ta
    - pandas_market_calendars
    - fracdiff
    - pydash
    - pudb
    - b2

# jupyter labextension install jupyterlab-tailwind-theme
