# conda env create --force -f conda_quant.yaml
# conda env update -n quant -f dev_ops/conda_quant.yaml

name: quant2
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.8
  - mkl
  - mamba
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - bokeh
  - pyarrow >= 4.0
  - pandas >= 1.2
  - pandas_market_calendars
  - ipython
  - ipdb
  - jupyterlab < 3.0
  - jupyterlab-git
  - nbdime
  - prefect
  - tqdm
  - tenacity
  - requests
  - fsspec
  - s3fs
  - pip
  - pip:
    - pandas-bokeh
    - 'ray[default]'
    - pudb
    - b2

# jupyter labextension install @jupyterlab/toc
# jupyter labextension install @jupyterlab/git
# jupyter labextension install nbdime-jupyterlab
# jupyter labextension install jupyterlab-execute-time
# pip install jupyterlab_execute_time [3.0+]
# jupyter labextension install @krassowski/jupyterlab_go_to_definition
# jupyter labextension install @jupyterlab/shortcutui
