# mamba env create --force -f dev_ops/conda_quant.yaml
# mamba env update -n quant -f dev_ops/conda_quant.yaml
name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.8
  - blas = *=mkl
  - psutil
  - mamba
  - numpy
  - scipy
  - scikit-learn
  - scikit-learn-intelex
  - imbalanced-learn
  - category_encoders
  - statsmodels
  - matplotlib
  - bokeh
  - yellowbrick
  - graphviz
  - pyarrow >= 4.0
  - pandas >= 1.2
  - pandas-profiling
  - pandas_market_calendars
  - ipython
  - ipdb
  - jupyterlab > 3.0
  - nodejs
  - jupyterlab-git
  - nbdime
  - jupyterlab_execute_time
  - prefect
  - dask
  # - 'modin[all]'
  # - mlflow
  # - shap
  # - pytorch
  # - mljar-supervised
  # - tpot
  # - pycaret
  # - xgboost
  # - catboost
  # - lightgbm
  - tqdm
  # - tenacity
  - requests
  - fsspec
  - s3fs
  - boto3
  - pip
  - pip:
    - pandas-bokeh
    - 'ray[default,tune,serve]'
    # - chefboost
    # - deep-forest
    # - pytorch-tabnet
    # - autoviml
    # - 'autogluon.tabular[all,skex]'
    # - tsai
    # - auto-sklearn
    - 'flaml[notebook]'
    # - polars
    - pandas_ta
    - fracdiff
    - pydash
    - pudb
    - b2

# jupyter labextension install @jupyterlab/toc
# jupyter labextension install @jupyterlab/git
# jupyter labextension install nbdime-jupyterlab
# jupyter labextension install jupyterlab-execute-time
# pip install jupyterlab_execute_time [3.0+]
# jupyter labextension install @krassowski/jupyterlab_go_to_definition
# jupyter labextension install @jupyterlab/shortcutui
