# conda env create --force -f dev_ops/conda_mlfinlab.yaml

name: mlfinlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.8
  - jupyterlab
  - pip
  - pip:
    - mlfinlab
    - portfoliolab
