# mamba env create --force -f dev_ops/conda_mlfinlab.yaml
# mamba env update -n quant -f dev_ops/conda_mlfinlab.yaml
name: mlfinlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.8
  - blas = *=mkl
  - mamba
  - jupyterlab
  - jupyterlab-git
  - nbdime
  - jupyterlab_execute_time
  - pip
  - pip:
    - mlfinlab
    - portfoliolab
